name: catalogocasamento
description: "Catalago para Casamento"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-172.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  brasil_fields: ^1.15.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  shared_preferences: ^2.2.3
  gif: ^2.3.0
  gif_view: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/icon/resetpassword.png
    - lib/assets/icon/couple.png
    - lib/assets/icon/present.png
    - lib/assets/gif/gifPresente.gif

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

